Added kitchen and food related classes
b-it-bots/mas_knowledge_base pull request #33
Opened 2020-05-02 17:21 UTC by samuelpg

* Added `KitchenUtensil` class with subclasses.
* Added `FoodOrDrink` class with subclasses.
* Added class `Drawer` to parent class `Furniture`
* Added more appliances sub-classes to `Appliance`

2020-05-02 17:27 UTC, alex-mitrevski requested changes
* Can you please make sure that the class definitions in `apartment.owl` and `homelab.owl` are in sync?
* Please delete `test.py`

2020-05-02 18:03 UTC, samuelpg commented
* Made `apartment.owl` consistent with `homelab.owl`
* deleted `test.py`

2020-05-02 18:05 UTC, alex-mitrevski requested changes

2020-05-02 18:05 UTC, alex-mitrevski commented on common/ontology/apartment.owl
> +        <owl:inverseOf rdf:resource="file:/home/samuel/Documents/MAS/b-it-bots/mas_knowledge_base/common/ontology/apartment.owl#apartment:above"/>
Can you please remove these local paths (here and everywhere below)?

2020-05-03 10:18 UTC, samuelpg commented
* Removed local paths in Object Properties

2020-05-04 13:15 UTC, alex-mitrevski approved these changes

2020-05-04 13:15 UTC, merged